<?php echo $this->headScript()->prependFile($this->basePath('js/jquery-ui-1.12.1/jquery-ui.js')); ?>
<?php  echo $this->headLink()->prependStylesheet($this->basePath('js/jquery-ui-themes-1.12.1/themes/black-tie/jquery-ui.css')); ?>

<script type="text/javascript">
    $(function(ready){
        $("#recalculate").click(function() {
            $.ajax({
                url: '/warehouse/stockmergement/recalculate/id/<?php echo $stock->getId();?>',
                type: 'POST',
                dataType: 'json',
                data: {},
                async: false,
                success: function (data) {
                    $("#stockqty").html(data.stockqty);
                }
            });
        });

    });

</script>

    <h1><?php echo $stock->getDescription() ?></h1>

    <?php
    echo '<hr>';

    echo '<h4>Equivalences:</h4>';
    echo '<table border="1" border-style="solid" border-color="black" width="50%" cellspacing=4 cellpadding=4>' ;
    echo '<tr>';
    echo '<th>Tablespoon</th>';
    echo '<th>Coffeespoon</th>';
    echo '<th>Teaspoon</th>';
    echo '<th>Pinch</th>';
    echo '<th>Piece</th>';
    echo '</tr>';
    echo '<tr>';
    echo '<td>'.$stock->getEqtblsp().'</td>';
    echo '<td>'.$stock->getEqcofsp().'</td>';
    echo '<td>'.$stock->getEqteasp().'</td>';
    echo '<td>'.$stock->getEqpinch().'</td>';
    echo '<td>'.$stock->getEqpiece().'</td>';
    echo '</tr>';
    echo '</table>';

    echo '<hr>';
    echo '<div name="stockqty" id="stockqty"><h4>Stock: ';
    if ($stock->getNetquantity() > 0) {
        echo '<font color="green">'.$stock->getNetquantity().$stock->getMeasureUnit()->getUnit().'</font>';
    }
    else {
        echo '<font color="red">'.$stock->getNetquantity().$stock->getMeasureUnit()->getUnit().'</font>';
    }
    echo '</h4></div>';
    echo '<button id="recalculate" name="recalculate">Recalculate</button>';
    echo '<table border="1" border-style="solid" border-color="black" width="70%" cellspacing=4 cellpadding=4>' ;
    echo '<tr>';
    echo '<th>Article</th>';
    echo '<th>Quantity</th>';
    echo '<th>Net Quantity</th>';
    echo '<th>Total Quantity</th>';
    echo '</tr>';

    foreach ($stockmerged as $st) {
        echo '<tr>';
        echo '<td>'.$st->getDescription();
        if ($st->getPrefered() == 1)
            echo ' - <font color="green">Prefered</font>';
        echo '</td>';
        echo '<td>'.$st->getQuantity().'</td>';
        echo '<td>'.$st->getNetQuantity().'</td>';
        echo '<td>'.$st->getQuantity() * $st->getNetQuantity().'</td>';
        echo '</tr>';
    }
    echo '</table>';

    echo '<hr>';
    echo '<p>Area: '.$stock->getArea()->getDescription().'</p>';
    echo '<p>Section: '.$stock->getSection()->getDescription().'</p>';
    echo '<p>Supplier: '.$stock->getSupplier()->getDescription().'</p>';

    echo '<hr>';

    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formInput($form->get('backToList'));
    echo ' '.$this->formInput($form->get('update'));
    echo ' '.$this->formInput($form->get('delete'));
    echo ' '.$this->formInput($form->get('add'));
    echo $this->form()->closeTag();

?>

<!-- empty div to save dialog temporary -->
<div id="winpopup">
    <?php
    if ($this->get('messages') != null) {
        foreach ($this->get('messages') as $inputName => $messageInputs) {
            echo '  <span id="error-form-message">' . $messageInputs . '</span>';
        }
    }
    ?>
</div>