<script type="text/javascript">
    $(function(ready){
        $("#area").on('change','select',function () {
            $.ajax({
                url:        '/warehouse/stockmergement/loadsectionvalues/id/'+document.getElementsByName("stock[area_id]")[0].value,
                type:       'POST',
                dataType:   'json',
                async:      false,
                success: function(data){
                    $('#section').html(data.section);
                },
                error : function(xhr, textStatus, errorThrown) {
                    if (xhr.status === 0) {
                        alert('Not connected. Verify Network.');
                    } else if (xhr.status == 404) {
                        alert('Requested page not found. [404]');
                    } else if (xhr.status == 500) {
                        alert('Server Error [500].');
                    } else if (errorThrown === 'parsererror') {
                        alert('Requested JSON parse failed.');
                    } else if (errorThrown === 'timeout') {
                        alert('Time out error.');
                    } else if (errorThrown === 'abort') {
                        alert('Ajax request aborted.');
                    } else {
                        alert('Remote sever unavailable. Please try later');
                    }
                }
            });
        });
    });
</script>

<h1>Update Stock</h1>

<?php
    $myStock = $this->stock;
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
?>

<p>Description: <?= $this->formTextarea($this->form->get('stockmergement')->get('description'));?></p>
<div><?=$this->formElementErrors($form->get('stockmergement')->get('description'), ['class' => 'custom_form_errors']);?></div>
<p>Measure Unit: <?=$this->formElement($this->form->get('stockmergement')->get('measureunit_id'));?></p>
<div><?=$this->formElementErrors($form->get('stockmergement')->get('measureunit_id'), ['class' => 'custom_form_errors']);?></div>
<hr>

<h4>Equivalences:</h4>
<table border="1" border-style="solid" border-color="black" width="50%" cellspacing=4 cellpadding=4>
    <tr>
        <th>Tablespoon</th>
        <th>Coffeespoon</th>
        <th>Teaspoon</th>
        <th>Pinch</th>
        <th>Piece</th>
    </tr>
    <tr>
        <td>
            <?=$this->formElement($this->form->get('stockmergement')->get('eqtblsp'));?>
            <div><?=$this->formElementErrors($form->get('stockmergement')->get('eqtblsp'), ['class' => 'custom_form_errors']);?></div>
        </td>
        <td>
            <?=$this->formElement($this->form->get('stockmergement')->get('eqcofsp'));?>
            <div><?=$this->formElementErrors($form->get('stockmergement')->get('eqcofsp'), ['class' => 'custom_form_errors']);?></div>
        </td>
        <td>
            <?=$this->formElement($this->form->get('stockmergement')->get('eqteasp'));?>
            <div><?=$this->formElementErrors($form->get('stockmergement')->get('eqteasp'), ['class' => 'custom_form_errors']);?></div>
        </td>
        <td>
            <?=$this->formElement($this->form->get('stockmergement')->get('eqpinch'));?>
            <div><?=$this->formElementErrors($form->get('stockmergement')->get('eqpinch'), ['class' => 'custom_form_errors']);?></div>
        </td>
        <td>
            <?=$this->formElement($this->form->get('stockmergement')->get('eqpiece'));?>
            <div><?=$this->formElementErrors($form->get('stockmergement')->get('eqpiece'), ['class' => 'custom_form_errors']);?></div>
        </td>
    </tr>
</table>

<hr>

<p>Area: <?=$this->formElement($this->form->get('stockmergement')->get('area_id'));?></p>
<div><?=$this->formElementErrors($form->get('stockmergement')->get('area_id'), ['class' => 'custom_form_errors']);?></div>
<div name="section" id="section">
    <p>
        Section: <?=$this->formElement($this->form->get('stockmergement')->get('section_id'));?>
    </p>
</div>
<div><?=$this->formElementErrors($form->get('stockmergement')->get('section_id'), ['class' => 'custom_form_errors']);?></div>
<p>
    Supplier: <?=$this->formElement($this->form->get('stockmergement')->get('supplier_id'));?>
</p>
<div><?=$this->formElementErrors($form->get('stockmergement')->get('supplier_id'), ['class' => 'custom_form_errors']);?></div>

<hr>

<?php
    echo $this->formInput($form->get('backToList'));
    echo ' '.$this->formInput($form->get('update'));
    echo ' '.$this->formInput($form->get('cancel'));
    echo $this->form()->closeTag();
?>
