<script type="text/javascript">
    $(function(ready){
        $("#critarea").on('change','select',function () {
//            alert('/warehouse/stock/critsectionvalues/id/'+document.getElementsByName("area")[0].value);
            $.ajax({
                url:        '/warehouse/stockmergement/critsectionvalues/id/'+document.getElementsByName("area")[0].value,
                type:       'POST',
                dataType:   'json',
                async:      false,
                //    data:       $("#stock[area_id]").serialize(),
                success: function(data){
                    $('#critsection').html(data.section);
                    //   alert($("#area :selected").text()); // The text content of the selected option
                    //   alert($("#area").val()); // The value of the selected option

                },
                error : function(xhr, textStatus, errorThrown) {
                    if (xhr.status === 0) {
                        alert('Not connected. Verify Network.');
                    } else if (xhr.status == 404) {
                        alert('Requested page not found. [404]');
                    } else if (xhr.status == 500) {
                        alert('Server Error [500].');
                    } else if (errorThrown === 'parsererror') {
                        alert('Requested JSON parse failed.');
                    } else if (errorThrown === 'timeout') {
                        alert('Time out error.');
                    } else if (errorThrown === 'abort') {
                        alert('Ajax request aborted.');
                    } else {
                        alert('Remote sever unavailable. Please try later');
                    }
                }
            });
        });
    });
</script>
<div class="criteriadata">
    <h1>Search</h1>
    <?php
    $form = $this->criteriastockmergementform;
    $form->prepare();

    echo $this->form()->openTag($form);                 //open form tag
    echo ('<div id="critarea"><p>Area:');
    echo $this->formSelect($form->get('area'));     //domain
    echo '</p></div>';
    echo $this->formSubmit($form->get('search'));       //search button
    echo ('<p></p>');
    echo ('<p>Description contents:</p>');
    echo $this->formRow($form->get('description'));     //description field
    echo ('<hr>');
    echo ('<p>Availability:</p>');                      //availability field
    echo $this->formSelect($form->get('availability'));
    echo ('<hr>');
    echo ('<p>Status:</p>');
    echo $this->formRadio($form->get('status'));        //status radio button
    echo ('<hr>');
    echo ('<p>Section:</p>');
    echo ('<div id="critsection">');
    $section = $form->get('section');                   //section checkboxes
    echo $this->formMultiCheckbox($section);
    echo ('</div>');
    echo $this->form()->closeTag();                     //close form tag
    ?>
</div>
<div class="listdata">
    <?php $paging = $this->paginationHelper($pagedStock, $page, '/warehouse/stockmergement/list/', 50); ?>
    <h1>Stock</h1>
    <table>
        <tr>
            <td>
                <form action="/warehouse/stockmergement/add">
                    <input name="new" type="submit"  id="new" value="New Stock">
                </form>
            </td>
            <td>
                <div name="file" id="file"></div>
            </td>
        </tr>
    </table>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Article description</th>
            <th>Quantity</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($pagedStock as $stockLine) { ?>
            <tr>
                <td><div class="col-md-10">
                        <a class="settingdetail" href="/warehouse/stockmergement/display/id/<?php echo $stockLine->getId(); ?>"><?php echo $stockLine->getDescription(); ?></a>
                    </div>
                </td>
                <td><div class="col-md-10"><?php
                        if ($stockLine->getNetquantity() <= 0)
                            echo ('<font color="red">'. $stockLine->getNetquantity().$stockLine->getUnit()->getUnit().'</font>');
                        else
                            echo ($stockLine->getNetquantity().$stockLine->getUnit()->getUnit());
                        ?>
                    </div></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <div class="paging">
        <?php if (sizeof($pagedStock) > 0) echo $paging; ?>
    </div>
</div>

<script type="text/javascript">
    $("#validButton").click(function() {
        var url = "/api/addressForm/validForm";
        $.ajax({
            type: "POST",
            url: url,
            data: $("#addressForm").serialize(),
            success: function(data)
            {
                $('.alert').hide();
                $('.form-group').removeClass("has-error");
                $('.form-group').addClass("has-success");
                console.log(data.isValid);
                if ( ! data.isValid) {
                    $.each(data.messages,function(index,inputMessages){
                        $.each(inputMessages,function(input,message) {
                            htmlError = message + '<br>';
                            id = "#" + index + "_error_message";
                            formGroupId = "#" + index + "_form_group";
                            $(id).html(htmlError);
                            $(id).show();
                            $(formGroupId).removeClass("has-success");
                            $(formGroupId).addClass("has-error");
                        });
                    });
                }
                else $("#addressForm").submit();
            }
        });
    });

    function exportxlslist(){
        event.preventDefault();
        $.ajax({
            url: '/warehouse/stockmergement/exportxls',
            type:       'POST',
            dataType:   'json',
            async:      false,
            success: function(data, status){
                $("#file").html(data.file);
            },
            error: function(xhr, status, errorThrown){
                if (xhr.status === 0) {
                    alert('Not connected. Verify Network.');
                } else if (xhr.status == 404) {
                    alert('Requested page not found. [404]');
                } else if (xhr.status == 500) {
                    alert('Server Error [500].');
                } else if (errorThrown === 'parsererror') {
                    alert('Requested JSON parse failed.');
                } else if (errorThrown === 'timeout') {
                    alert('Time out error.');
                } else if (errorThrown === 'abort') {
                    alert('Ajax request aborted.');
                } else {
                    alert('Remote sever unavailable. Please try later');
                }
            },
            complete: function(xhr, textStatus) {
                //       alert(textStatus);
            }
        });
    }

    function OpenRLink(l){
        window.open(l);
    }

</script>

