<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('success', ['action' => 'index',]));
$form->prepare();
echo $this->form()->openTag($form);
echo '<table>';
echo '<tr><td width="130" valign="middle">';
echo 'Old password: ';
echo '</td>';
echo '<td align="right">';
echo '<div>'.$this->formElement($form->get('password')->get('password')).'</div>';
echo '</td></tr>';
echo '<tr><td></td>';
echo '<td>';
echo '<div>'.$this->formElementErrors($form->get('password')->get('password'), array('class' => 'custom_form_errors')).'</div>';
echo '</td></tr>';
echo '<tr><td width="130" valign="middle">';
echo $form->get('password')->get('newpassword1')->getLabel();
echo '</td>';
echo '<td align="right">';
echo $this->formInput($form->get('password')->get('newpassword1'));
echo '</td</tr>';
echo '<tr><td></td>';
echo '<td>';
echo '<div>'.$this->formElementErrors($form->get('password')->get('newpassword1'), array('class' => 'custom_form_errors')).'</div>';
echo '</td></tr>';
echo '<tr><td width="130" valign="middle">';
echo $form->get('password')->get('newpassword2')->getLabel();
echo '</td>';
echo '<td align="right">';
echo $this->formInput($form->get('password')->get('newpassword2'));
echo '</td</tr>';
echo '<tr><td></td>';
echo '<td>';
echo '<div>'.$this->formElementErrors($form->get('password')->get('newpassword2'), array('class' => 'custom_form_errors')).'</div>';
echo '</td></tr>';
echo '<tr>';
echo '<td colspan="3" align="right"><span id="error-form-message">';
if ($this->messages) {
    foreach($this->messages as $message) {
        echo $message;
    }
}
if ($this->flashmessages) {
    echo '</span>';
    echo '<span class="custom_form_info">';
    foreach($this->flashmessages as $message) {
        echo $message;
    }
}
echo '</span></td>';
echo '</tr>';
echo '<tr>';
echo '<td colspan="2" align="right">';
echo $this->formInput($form->get('update'));
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td colspan="2">';
echo '</td>';
echo '</table>';

echo $this->form()->closeTag();
?>