<?php echo $this->headScript()->prependFile($this->basePath('js/jquery-ui-1.12.1/jquery-ui.js')); ?>
<?php  echo $this->headLink()->prependStylesheet($this->basePath('js/jquery-ui-themes-1.12.1/themes/black-tie/jquery-ui.css')); ?>

<script type="text/javascript">
    function RenameAttachment(attachId){
        event.preventDefault();
        $attachmentId= attachId;
        $fileName= $('#description' + attachId).val();
        $.ajax({
            url: '/warehouse/attachment/changedescription/id/'+attachId,
            type:       'POST',
            dataType:   'json',
            async:      false,
            data:       'file-label=' + $fileName,
            success: function(data){
                $("#infoattachment").html(data.message);
            }
        });
    }

    function exportpdf(id){
        event.preventDefault();
        $.ajax({
            url: '/warehouse/recipe/generatepdf/id/'+id,
            type:       'POST',
            //dataType:   'json',
            async:      false,
            success: function(data, status){
                $("#file").html(data.file+' '+data.msg);
            },
            error: function(xhr, status, errorThrown){
                if (xhr.status === 0) {
                    alert('Not connected. Verify Network.');
                } else if (xhr.status == 404) {
                    alert('Requested page not found. [404]');
                } else if (xhr.status == 500) {
                    alert('Server Error [500].');
                } else if (errorThrown === 'parsererror') {
                    alert('Requested JSON parse failed.');
                } else if (errorThrown === 'timeout') {
                    alert('Time out error.');
                } else if (errorThrown === 'abort') {
                    alert('Ajax request aborted.');
                } else {
                    alert('Remote sever unavailable. Please try later');
                }
            },
            complete: function(xhr, textStatus) {
            }
        });
    }

    function OpenRLink(l){
        window.open(l);
    }
</script>

<table>
    <tr>
        <td>
            <h1><?= $recipe->getDescription(); ?></h1>
            <div>
                <p>
                    <i>Serves:</i> <?= $recipe->getServes(); ?> - <i>Preparation time:</i>
                    <?= $recipe->getPreparationTime(); ?>
                     - <i>Total time:</i>
                    <?= $recipe->getTotalTime(); ?>
                     - <i>Category</i>: <?= $recipe->getCategory()->getDescription(); ?>
                </p>
            </div>
        </td>
        <td style="padding: 0px 0px 0px 50px;">
        </td>
        <td style="padding: 0px 0px 0px 0px;">
            <?php
            $photoAttachment= $this->defaultphoto;
            if (isset($photoAttachment)) {
                echo '<img style="max-height: 120px; width: auto;" src="'. $this->urlthumb . '/' .$photoAttachment->getFileName().'" id="defaultphoto" alt="'.$recipe->getDescription().'"/>';
            } else {
                echo '<img style="max-height: 120px; width: auto;" src="../../../../img/takephoto.png" id="defaultphoto" alt="The photo does not exist"/>';
            }
            ?>
        </td>
    </tr>
</table>

<table>
    <tr>
        <td>
            <input name="exportpdf" type="button" onclick="exportpdf(<?= $recipe->getId(); ?>);" id="exportpdf" value="Export PDF">
        </td>
        <td>
            <div name="file" id="file"></div>
        </td>
    </tr>
</table>

<h4>Notes/Suggestions:</h4><?= $recipe->getNote(); ?>

<h4>Ingredients
    <a title="Add the \'Not on stock\' ingredients to the shopping list" class="shoppinglist" href="/warehouse/recipe/shoppinglist/id/<?= $recipe->getId(); ?>?from=recipe"><img style="max-height: 18px; width: auto;" src="../../../../img/caddie.png" id="buy" alt=""/></a>
    <a title="Add the \'Out to stock\' list" class="stockinterface" href="/warehouse/recipe/stockinterface/id/<?= $recipe->getId(); ?>?from=recipe"><img style="max-height: 18px; width: auto;" src="../../../../img/toque2.jpg" id="out" alt=""/></a>
</h4>

<ul>
    <?php foreach($recipe->getIngredients() as $ingredient): ?>
        <li>
            <?php
            if ($ingredient->getQuantity() == round($ingredient->getQuantity(),0)) {
                echo round($ingredient->getQuantity(), 0);
            } else {
                echo $ingredient->getQuantity();
            }
            ?>
            <?= ' ' . $ingredient->getMeasureUnit()->getUnit().' '. $ingredient->getStockmergement()->getDescription(); ?>
            - <?= $ingredient->getDescription(); ?>

            <?php
            switch ($ingredient->getAvailability()){
                case \Warehouse\Controller\StockmergementController::ON_STOCK:
                    echo ('<font color="green">   => On Stock</font>');
                    break;
                case \Warehouse\Controller\StockmergementController::NOT_ON_STOCK:
                    echo ('<font color="red"><b>   => Not On Stock</b></font>');
                    break;
                case \Warehouse\Controller\StockmergementController::ON_STOCK_REQUIRE_MANUAL_CHECK:
                    echo ('<font color="green">   => On Stock - </font><font color="orange">Require manual check for exact quantity</font>');
                    break;
            }
            ?>
        </li>
    <?php endforeach; ?>

</ul>

<h4>Instructions</h4>
<ol>
    <?php foreach($recipe->getInstructions() as $instruction): ?>
    <li>
        <?= $instruction->getDescription(); ?>
    </li>
    <?php endforeach; ?>
</ol>

<hr>

<h4>Attachments</h4>
<form method="POST" name="upload-file-form" enctype="multipart/form-data" action="/warehouse/recipeattachment/add/id/<?= $recipe->getId(); ?>" id="upload-file-form">
    <div class="form-element">
        <input type="file" name="uploaded-file[]" id="uploaded-file">
    </div>
    <button name="add">Add attachment</button>
    <button name="cancel">Cancel</button>
    <input type="text" name="file-label" id="file-label" placeholder="File description"/>
</form>

<span id="error-form-message">
<?php
if ($this->flashmessages) {
    foreach($this->flashmessages as $message) {
        echo $message['message'];
    }
}
?>
</span>
<div id="infoattachment" class="div-info-form-message">
</div>

<?php if (0 === count($recipe->getAttachment())): ?>
    <p><i>none</i></p>
<?php endif; ?>

<?php if (0 !== count($recipe->getAttachment())): ?>
<table border="1" border-style="solid" border-color="black" width="65%" cellspacing=4 cellpadding=4>
    <tr>
        <th>Description</th>
        <th>File Name</th>
        <th>Size</th>
        <th>Mime</th>
        <th>Default Photo</th>
        <th></th>
        <th></th>
    </tr>

    <?php foreach($recipe->getAttachment() as $attachment): ?>
    <tr>
        <td>
            <input type="text" name="description<?=$attachment->getId();?>" id="description<?=$attachment->getId();?>" value="<?=$attachment->getDescription();?>">
            <a id="fileRename" onclick="RenameAttachment(<?=$attachment->getId();?>);" href=""><img style="max-height: 18px; width: auto;" src="../../../../img/edit.jpeg" id="edit" alt=""/></a>
        </td>

        <td><?= $attachment->getFileName(); ?></td>
        <td><?= round($attachment->getSize() / 1000000, 2); ?> MB</td>
        <td><?= $attachment->getMime(); ?></td>

        <?php if ('1' == $attachment->getDefaultPhoto()): ?>
            <td align="center">
                <img style="max-height: 18px; width: auto;" src="../../../../img/checkmark.png" id="isdefaultphoto" alt=""/>
            </td>
        <?php endif; ?>

        <?php if ('1' != $attachment->getDefaultPhoto()): ?>
            <td align="center">
            <?php if ('image/png' === $attachment->getMime() or 'image/bmp' === $attachment->getMime() or 'image/jpeg' === $attachment->getMime() or 'image/gif' === $attachment->getMime() or 'image/tiff' === $attachment->getMime()): ?>
                <a id="choosedefaultphoto" href="/warehouse/recipeattachment/changedefaultphoto/id/<?= $attachment->getId(); ?>?recipe_id=<?=$recipe->getId();?>">
                    <img style="max-height: 18px; width: auto;" src="../../../../img/choose2.png" id="choosedefaultphoto" alt=""/>
                </a>
            <?php endif; ?>
            </td>
        <?php endif; ?>

        <td align="center">
            <a class="filePreview" href="/warehouse/attachment/open/id/<?= $attachment->getId(); ?>" target="_blank">
                <img style="max-height: 18px; width: auto;" src="../../../../img/view.ico" id="view" alt=""/>
            </a>
        </td>
        <td align="center">
            <a id="fileDelete" href="/warehouse/recipeattachment/delete/id/<?= $attachment->getId(); ?>?recipe_id=<?=$recipe->getId();?>">
                <img style="max-height: 18px; width: auto;" src="../../../../img/trash.png" id="delete" alt=""/>
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>


<hr>

<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formInput($form->get('backToList'));
echo ' '.$this->formInput($form->get('update'));
echo ' '.$this->formInput($form->get('check'));
echo ' '.$this->formInput($form->get('delete'));
echo ' '.$this->formInput($form->get('add'));
echo $this->form()->closeTag();

?>

<!-- empty div to save dialog temporary -->
<div id="winpopup">
    <?php
    if ($this->get('messages') != null) {
        foreach ($this->get('messages') as $inputName => $messageInputs) {
            echo '  <span id="error-form-message">' . $messageInputs . '</span>';
        }
    }
    ?>
</div>
