    <table>
        <tr>
            <td>
                <?php
                $photoAttachment= $this->defaultphoto;
                if (isset($photoAttachment)) {
                 echo '<img style="max-height: 80px; width: auto;" src="../../../../'.$photoAttachment->getPath().$photoAttachment->getFileName().'" id="defaultphoto" alt=""/>';
                } else {
                    echo '<img style="max-height: 80px; width: auto;" src="../../../../img/takephoto.png" id="defaultphoto" alt="The photo does not exist"/>';
                }
                ?>
            </td>
            <td>
                <h1>
                    <?php echo $stock->getDescription() ?></h1>
                <h5>Status: <?php
                    if ($stock->getStatus() == \Warehouse\Enum\EnumStatus::Enabled) {
                        echo '<font color="green">Enabled</font>';
                    }
                    else {
                        echo '<font color="red">Disabled</font>';
                    }
                    ?></h5>
            </td>
            <td>
                <?php
                    echo '<img src="/warehouse/stock/barcode/id/'.$stock->getBarcode().'"/>';
                ?>
            </td>
        </tr>
    </table>
    <?php
    echo '<hr>';
    echo '<table border="1" border-style="solid" border-color="black" width="50%" cellspacing=4 cellpadding=4>' ;
    echo '<tr>';
    echo '<td><p>Area: '.$stock->getArea()->getDescription().'</p></td>';
    echo '<td><p>Section: '.$stock->getSection()->getDescription().'</p></td>';
    echo '<td><p>Supplier: '.$stock->getShop()->getDescription().'</p></td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td><p>Current stock: ';
        if ($stock->getQuantity() > 0) {
            echo '<font color="green">'.$stock->getQuantity().'</font>';
        }
        else {
            echo '<font color="red">'.$stock->getQuantity().'</font>';
        }
    echo '</p></td>';
    echo '<td><p>Info Threshold: '.$stock->getInfothreshold().'</p></td>';
    echo '<td><p>Critical Threshold: '.$stock->getCriticalthreshold().'</p></td>';
    echo '</tr>';
    echo '</table>';

    echo '<hr>';

    echo '<h4>Merger</h4>';

    if ($stock->getBarcodemerger() != 0){
        if ($stock->getBarcodemerger() == $stock->getBarcode()){
            echo '<p>List of merged products:</p>';
        } else {
            echo '<p>Merge on: '.$stock->getBarcodemerger().' - for a total quantity of: '.$stock->getMergedquantity().'</p>';
        }
    } else {
        echo '<p>none</p>';
    }
    echo '<hr>';
    echo '<h4>Attachments</h4>';
    $formUploadFile = $this->formuploadedfile;
    $formUploadFile->prepare(); // The correct enctype is set here
    $formUploadFile->setAttribute('action', '/warehouse/stock/uploadfile/id/'.$stock->getId());
    echo $this->form()->openTag($formUploadFile);
    echo '<div class="form-element">';
    $fileElement = $formUploadFile->get('uploaded-file');
    echo $this->formFile($fileElement);
    echo $this->formElementErrors($fileElement);
    echo 'Description: '.$this->formInput($formUploadFile->get('attachment-description'));
    echo 'Default photo: '.$this->formInput($formUploadFile->get('chk-defaultphoto'));
    echo '</div>';
    echo '<input type="submit"  id="submit-btn" value="Add new attachment" />';
    echo '<div class="upload-message" id="upload-message"></div>';
    echo $this->form()->closeTag();

    foreach ($form->getMessages() as $msg){
        echo $msg;
    }


    echo '<table border="1" border-style="solid" border-color="black" width="65%" cellspacing=4 cellpadding=4>';
    echo '<tr>';
    echo '<th>Description</th>';
    echo '<th>File Name</th>';
    echo '<th>Size</th>';
    echo '<th>Mime</th>';
    echo '<th>Default Photo</th>';
    echo '<th></th>';
    echo '</tr>';
    foreach ($stock->getAttachment() as $attachment) {
        echo '<tr>';
        $date = date_format(new \DateTime('now'),"Y/m/d");
        if (date_format($attachment->getCreationDate(),"Y/m/d") >= $date) {
            echo '<td>' . $attachment->getDescription() . '<img style="max-height: 18px; width: auto;" src="../../../../img/new.png" id="new" alt="New attachment"/></td>';
        } else {
            echo '<td>' . $attachment->getDescription() .'</td>';
        }
        echo '<td>'.$attachment->getFileName().'</td>';
        if ($attachment->getSize() >= 1000000) {
            $size = round($attachment->getSize() / 1000000, 2) . ' MB';
        } else {
            $size = round($attachment->getSize() / 1000, 2) . ' KB';
        }
        echo '<td>'.$size.'</td>';
        echo '<td>'.$attachment->getMime().'</td>';
        if ($attachment->getDefaultPhoto() == '1') {
            echo '<td align="center"><img style="max-height: 18px; width: auto;" src="../../../../img/checkmark.png" id="isdefaultphoto" alt=""/></td>';
        } else {
            echo '<td></td>';
        }
        echo '<td><a class="filePreview" href="/warehouse/attachment/open/id/'.$attachment->getId().'" target="_blank">View</a></td>';
        echo '</tr>';
    }
    echo '</table>';
echo '<hr>';

$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formInput($form->get('backToList'));
echo ' '.$this->formInput($form->get('update'));
echo ' '.$this->formInput($form->get('delete'));
echo ' '.$this->formInput($form->get('add'));
echo $this->form()->closeTag();

?>
