<?php echo $this->headScript()->prependFile($this->basePath('js/jquery-ui-1.12.1/jquery-ui.js')); ?>
<?php  echo $this->headLink()->prependStylesheet($this->basePath('js/jquery-ui-themes-1.12.1/themes/black-tie/jquery-ui.css')); ?>

<script type="text/javascript">
    $(function(ready){
        $("#showform").click(function(){
            $.ajax({
                url: '/warehouse/attachment/openupload/id/<?php echo $stock->getId();?>',
                type:       'POST',
                dataType:   'json',
                data:       'defaultphoto=1',
                async:      false,
                success: function(data){
                    $("#winpopup").html(data.contentpage);
                }
            });
            //create an instance of dialog box, without opening it
            $("#winpopup").dialog({
                draggable:true,
                autoOpen: false,
                height:250,
                width:400,
                modal: true,
                resizable: false,
                title:'Upload a file'
            });
            //open the dialog box
            $("#winpopup").dialog('open');
            return false;
        });

        $("#newattachment").click(function(){
            $.ajax({
                url: '/warehouse/attachment/openupload/id/<?php echo $stock->getId();?>',
                type:       'POST',
                dataType:   'json',
                data:       {'defaultphoto' : 0},
                async:      false,
                success: function(data){
                    $("#winpopup").html(data.contentpage);
                }
            });
            //create an instance of dialog box, without opening it
            $("#winpopup").dialog({
                draggable:true,
                autoOpen: false,
                height:300,
                width:400,
                modal: true,
                resizable: false,
                title:'Upload a file'
            });
            //open the dialog box
            $("#winpopup").dialog('open');
            return false;
        });
    });

    function RenameAttachment(id){
        event.preventDefault();
        $.ajax({
            url: '/warehouse/attachment/renamefile/id/'+id,
            type:       'POST',
            dataType:   'json',
            async:      false,
            success: function(data){
                $("#winpopup").html(data.contentpage);
            }
        });
        //create an instance of dialog box, without opening it
        $("#winpopup").dialog({
            draggable:true,
            autoOpen: false,
            height:250,
            width:600,
            modal: true,
            resizable: false,
            title:'Change the file description'
        });
        //open the dialog box
        $("#winpopup").dialog('open');
        return false;
    }

    function DeleteAttachment(id,defaultphoto) {
     //   event.preventDefault();
        if (defaultphoto == 1) msg = "Are you sure you want to delete the attachment because it is the current article photo?";
        else msg = "Are you sure you want to delete the attachment?";
        if (confirm(msg)){
            $.ajax({
                url: '/warehouse/attachment/delete/id/'+id,
                type:       'POST',
                dataType:   'json',
                async:      false,
                success: function(data, status){
              //      alert(data.msg);
                    $("#infoattachment").html(data.msg);
                },
                error: function(xhr, status, errorThrown){
                    if (xhr.status === 0) {
                        alert('Not connected. Verify Network.');
                    } else if (xhr.status == 404) {
                        alert('Requested page not found. [404]');
                    } else if (xhr.status == 500) {
                        alert('Server Error [500].');
                    } else if (errorThrown === 'parsererror') {
                        alert('Requested JSON parse failed.');
                    } else if (errorThrown === 'timeout') {
                        alert('Time out error.');
                    } else if (errorThrown === 'abort') {
                        alert('Ajax request aborted.');
                    } else {
                        alert('Remote sever unavailable. Please try later');
                    }
                },
                complete: function(xhr, textStatus) {
                }
            });
        }
    }

    function ChooseDefaultPhoto(id){
        $.ajax({
            url: '/warehouse/attachment/changedefaultphoto/id/'+id,
            type:       'POST',
            async:      false,
            success: function(data, status){

            },
            error: function(xhr, status, errorThrown){
                if (xhr.status === 0) {
                    alert('Not connected. Verify Network.');
                } else if (xhr.status == 404) {
                    alert('Requested page not found. [404]');
                } else if (xhr.status == 500) {
                    alert('Server Error [500].');
                } else if (errorThrown === 'parsererror') {
                    alert('Requested JSON parse failed.');
                } else if (errorThrown === 'timeout') {
                    alert('Time out error.');
                } else if (errorThrown === 'abort') {
                    alert('Ajax request aborted.');
                } else {
                    alert('Remote sever unavailable. Please try later');
                }
            },
            complete: function(xhr, textStatus) {
            }
        });
    }


</script>
    <table>
        <tr>
            <td>
                <?php
                $photoAttachment= $this->defaultphoto;
                if (isset($photoAttachment)) {
                 echo '<a id="showform" href=""><img style="max-height: 80px; width: auto;" src="../../../../'.$photoAttachment->getPath().$photoAttachment->getFileName().'" id="defaultphoto" alt=""/></a>';
                } else {
                    echo '<a id="showform" href=""><img style="max-height: 80px; width: auto;" src="../../../../img/takephoto.png" id="defaultphoto" alt="The photo does not exist"/></a>';
                }
                ?>
            </td>
            <td>
                <h1>
                    <?php echo $stock->getDescription() ?></h1>
                <h5>Status: <?php
                    if ($stock->getStatus() == \Warehouse\Enum\EnumStatus::Enabled) {
                        echo '<font color="green">Enabled</font>';
                        if ($stock->getPrefered() == 1) {
                            echo '<font color="black"> - Prefered</font>';
                        }
                    }
                    else {
                        echo '<font color="red">Disabled</font>';
                        if ($stock->getPrefered() == 1) {
                            echo '<font color="black"> - Prefered</font>';
                        }
                    }
                    ?></h5>
            </td>
            <td>
                <?php
                    echo '<img src="/warehouse/stock/barcode/id/'.$stock->getBarcode().'"/>';
                ?>
            </td>
        </tr>
    </table>
    <?php
    echo '<hr>';
    if ($stock->getMerge() != null) {
        echo '<p>Short description: ' . $stock->getMerge()->getDescription() . ' / Area: ' . $stock->getMerge()->getArea()->getDescription() . ' / Section: ' . $stock->getMerge()->getSection()->getDescription() . ' / Supplier: ' . $stock->getMerge()->getSupplier()->getDescription().'</p>';
    } else {
        echo '<p>Short description: <i>none</i></p>';
    }
    if ($stock->getSupplierReference() !== '') {
        echo '<p>Supplier reference: ' . $stock->getSupplierReference() . '</p>';
    } else {
        echo '<p>Supplier reference: <i>none</i></p>';
    }
    echo '<p>Notes: ';
    if ($stock->getNotes() == '') echo '<i>none</i></p>';
    else echo $stock->getNotes().'</p>';

    echo '<table border="1" border-style="solid" border-color="black" width="50%" cellspacing=4 cellpadding=4>' ;
    echo '<tr>';
    echo '<td><p>Current stock: ';
        if ($stock->getQuantity() > 0) {
            echo '<font color="green">'.$stock->getQuantity().'</font>';
        }
        else {
            echo '<font color="red">'.$stock->getQuantity().'</font>';
        }
    if ($stock->getMerge() != null)
        echo '</p><p>Net Quantity: '.$stock->getNetquantity().$stock->getMerge()->getUnit()->getUnit().'</p>';
    else
        echo '</p><p>Net Quantity: 0</p>';
    echo '</p></td>';
    echo '<td><p>Info Threshold: '.$stock->getInfothreshold().'</p></td>';
    echo '<td><p>Critical Threshold: '.$stock->getCriticalthreshold().'</p></td>';
    echo '</tr>';
    echo '</table>';

    echo '<hr>';

    echo '<h4>Attachments</h4>';
    echo '<button id="newattachment">New</button>';
    if (count($stock->getAttachment())==0) {
        echo '<p><i>none</i></p>';
    } else {
        echo '<table border="1" border-style="solid" border-color="black" width="65%" cellspacing=4 cellpadding=4>';
        echo '<tr>';
        echo '<th>Description</th>';
        echo '<th>File Name</th>';
        echo '<th>Size</th>';
        echo '<th>Mime</th>';
        echo '<th>Default Photo</th>';
        echo '<th></th>';
        echo '<th></th>';
        echo '<th></th>';
        echo '</tr>';
        foreach ($stock->getAttachment() as $attachment) {
            echo '<tr>';
            $date = date_format(new \DateTime('now'), "Y/m/d");
            if (date_format($attachment->getCreationDate(), "Y/m/d") >= $date) {
                echo '<td>' . $attachment->getDescription() . '<img style="max-height: 18px; width: auto;" src="../../../../img/new.png" id="new" alt="New attachment"/></td>';
            } else {
                echo '<td>' . $attachment->getDescription() . '</td>';
            }
            echo '<td>' . $attachment->getFileName() . '</td>';
            if ($attachment->getSize() >= 1000000) {
                $size = round($attachment->getSize() / 1000000, 2) . ' MB';
            } else {
                $size = round($attachment->getSize() / 1000, 2) . ' KB';
            }
            echo '<td>' . $size . '</td>';
            echo '<td>' . $attachment->getMime() . '</td>';
            if ($attachment->getDefaultPhoto() == '1') {
                echo '<td align="center"><img style="max-height: 18px; width: auto;" src="../../../../img/checkmark.png" id="isdefaultphoto" alt=""/></td>';
            } else {
                if ($attachment->getMime() == 'image/png' or $attachment->getMime() == 'image/bmp' or $attachment->getMime() == 'image/jpeg' or $attachment->getMime() == 'image/gif' or $attachment->getMime() == 'image/tiff'){
                    echo '<td align="center"><a id="choosedefaultphoto" onclick="ChooseDefaultPhoto('.$attachment->getId().');" href=""><img style="max-height: 18px; width: auto;" src="../../../../img/choose2.png" id="choosedefaultphoto" alt=""/></a></td>';
                } else {
                    echo '<td></td>';
                }
            }
            echo '<td align="center"><a class="filePreview" href="/warehouse/attachment/open/id/' . $attachment->getId() . '" target="_blank"><img style="max-height: 18px; width: auto;" src="../../../../img/view.ico" id="view" alt=""/></a></td> ';
            echo '<td align="center"><a id="fileDelete" onclick="DeleteAttachment('.$attachment->getId().','.$attachment->getDefaultPhoto().');" href=""><img style="max-height: 18px; width: auto;" src="../../../../img/trash.png" id="delete" alt=""/></a> </td>';
            echo '<td align="center"><a id="fileRename" onclick="RenameAttachment('.$attachment->getId().');" href=""><img style="max-height: 18px; width: auto;" src="../../../../img/edit.jpeg" id="edit" alt=""/></a></td>';
            echo '</tr>';
        }
        echo '</table>';
    }
    echo '<div id="infoattachment"></div>';
    echo '<hr>';
    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formInput($form->get('backToList'));
    echo ' '.$this->formInput($form->get('update'));
    echo ' '.$this->formInput($form->get('delete'));
    echo ' '.$this->formInput($form->get('add'));
    echo $this->form()->closeTag();

?>

<!-- empty div to save dialog temporary -->
<div id="winpopup">
    <?php
    if ($this->get('messages') != null) {
        foreach ($this->get('messages') as $inputName => $messageInputs) {
            echo '  <span id="error-form-message">' . $messageInputs . '</span>';
        }
    }
    ?>
</div>