<?php echo $this->headScript()->prependFile($this->basePath('js/jquery-ui-1.12.1/jquery-ui.js')); ?>
<?php  echo $this->headLink()->prependStylesheet($this->basePath('js/jquery-ui-themes-1.12.1/themes/black-tie/jquery-ui.css')); ?>

<script type="text/javascript">
    $(function(ready){

        $("#showform").click(function(){
            $.ajax({
                url: "/warehouse/attachment/openupload",
                type:       'POST',
                dataType:   'json',
                async:      false,
                success: function(data){
                    $("#winpopup").html(data.contentpage);
                }
            });
            //create an instance of dialog box, without opening it
            $("#winpopup").dialog({
                draggable:true,
                autoOpen: false,
                height:300,
                width:400,
                modal: true,
                resizable: false,
                title:'Upload a file'
            });
            //open the dialog box
            $("#winpopup").dialog('open');
            return false;
        });
    });
</script>


<h4>Attachments</h4>

<?php
$formUploadFile = $this->formuploadedfile;
$formUploadFile->prepare(); // The correct enctype is set here
$formUploadFile->setAttribute('action', '/warehouse/test/uploadfile');
echo $this->form()->openTag($formUploadFile);
//   echo $this->formFileSessionProgress(); // Must come before the file input!

echo '<div class="form-element">';
    $fileElement = $formUploadFile->get('attachment-file');
    //echo $this->formLabel($fileElement);
    echo $this->formFile($fileElement);
    echo $this->formElementErrors($fileElement);
    echo '</div>';
echo '<button>Add new attachment</button>';
echo $this->form()->closeTag();

echo '<br><br><button id="uploadbutton">Upload</button>';
?>
<br>
<a id="showform" href="">Upload File</a>

<!-- empty div to save dialog temporary -->
<div id="winpopup">
</div>


