<div class="listsettingsdata">
    <h1>Settings</h1>
    <?php
    $form = $this->settingsForm;
    $form->prepare();
    ?>
    <p><a href="/warehouse/settings/list?table=Area">Area</a></p>
    <p><a href="/warehouse/settings/list?table=MeasureUnit">Measure Unit</a></p>
    <p><a href="/warehouse/settings/list?table=Supplier">Supplier</a></p>
    <p><a href="/warehouse/settings/list?table=Section">Section</a></p>
    <p><a href="/warehouse/settings/list?table=Category">Recipe Category</a></p>
    <hr><p><a href="/warehouse/settings/list?table=Appsettings">Application Settings</a></p>
</div>

<div class="settingsdata">
    <div class="listsettingsdetail">

<?php switch ($table): ?>
<?php case \Warehouse\Enum\EnumTableSettings::MEASUREUNIT: ?>
    <h1>Measure Unit</h1>
    <input name="new" type="button" onclick="newSetting()" id="new" value="New Measure Unit">
    <?php break; ?>
<?php case \Warehouse\Enum\EnumTableSettings::SUPPLIER: ?>
    <h1>Supplier</h1>
    <input name="new" type="button" onclick="newSetting()" id="new" value="New Supplier">
    <?php break; ?>
<?php case \Warehouse\Enum\EnumTableSettings::SECTION: ?>
    <h1>Section</h1>
    <input name="new" type="button" onclick="newSetting()" id="new" value="New Section">
    <?php break; ?>
<?php case \Warehouse\Enum\EnumTableSettings::AREA: ?>
    <h1>Area</h1>
    <input name="new" type="button" onclick="newSetting()" id="new" value="New Area">
    <?php break; ?>
<?php case \Warehouse\Enum\EnumTableSettings::RECIPE_CATEGORY: ?>
    <h1>Recipe Category</h1>
    <input name="new" type="button" onclick="newSetting()" id="new" value="New Recipe Category">
    <?php break; ?>
<?php case \Warehouse\Enum\EnumTableSettings::APPSETTINGS: ?>
    <h1>Application Settings</h1>
    <input name="new" type="button" onclick="newSetting()" id="new" value="New Application Setting">
    <?php break; ?>
<?php endswitch ?>

        <div class="detailsettings">
        </div>

        <hr>

        <table class="table table-striped">
            <thead>
            <tr>
                <?php if ($table == \Warehouse\Enum\EnumTableSettings::APPSETTINGS): ?>
                    <th>Reference</th>
                    <th>Value</th>
                <?php else: ?>
                    <th>Description</th>
                    <?php if (strcmp($table, \Warehouse\Enum\EnumTableSettings::MEASUREUNIT) == 0): ?>
                        <th>Abbreviation</th><th>Available in Stock</th>
                    <?php endif; ?>
                    <?php if (strcmp($table, \Warehouse\Enum\EnumTableSettings::SECTION) == 0): ?>
                        <th>Area</th>
                    <?php endif; ?>
                    <th></th>
                <?php endif; ?>
            </tr>
            </thead>
            <tbody>
            <?php foreach($settings as $setting): ?>
                <tr>
                    <?php if ($table == \Warehouse\Enum\EnumTableSettings::APPSETTINGS): ?>
                        <td>
                            <div class="col-md-10">
                                <a class="settingdetail" href="?table=<?=$table;?>" id="<?=$setting['id'];?>">
                                    <?=$setting['settingreference'];?>
                                </a>
                            </div>
                        </td>
                        <td>
                        <?=$setting['settingvalue'];?>
                        </td>
                    <?php else: ?>
                        <td>
                            <div class="col-md-10">
                                <a class="settingdetail" href="?table=<?=$table;?>" id="<?=$setting['id'];?>">
                                    <?=$setting['description'];?>
                                </a>
                            </div>
                        </td>
                        <?php if (strcmp($table, \Warehouse\Enum\EnumTableSettings::MEASUREUNIT) == 0): ?>
                            <td><?=$setting['unit'];?></td>
                            <?php if ($setting['useinstock'] == 1): ?>
                            <td>
                                <input type="checkbox" id="<?=$setting['id'];?>_useinstock" value="Use in stock" checked disabled/>
                            </td>
                            <?php else: ?>
                            <td>
                                <input type="checkbox" id="<?=$setting['id'];?>_useinstock" value="Use in stock"  disabled/>
                            </td>
                            <?php endif; ?>
                            <?php if (strcmp($table, \Warehouse\Enum\EnumTableSettings::SECTION) == 0): ?>
                                <td><?=$setting['area']['description'];?></td>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <td>
                        <a id="setDelete" onclick="DeleteSetting(<?=$setting['id'];?>);" href="">
                            <img style="max-height: 18px; width: auto;" src="../../../../img/trash.png" id="delete" alt=""/>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
           </tbody>
        </table>

    </div>
    <input type="hidden" id="table" value="<?=$table;?>">

</div>

<script type="text/javascript">
    $(document).ready(function()
    {
        $(".settingdetail").click(function(){
            var this_id=$(this).attr("id");
            var this_href=$(this).attr("href");
            $.ajax({
                url: "/warehouse/settings/edit/id/"+this_id+this_href,
                type: "POST",
                dataType: "json",
                async: false,
                success:function(data) {
                    $(".detailsettings").html(data.contentpage);
                }
            });
            return false;
        });
    });

    function updateSetting(){
        $.ajax({
            url: "/warehouse/settings/update/id/"+$("#id").val()+'?table='+$("#table").val(),
            type: "POST",
            async: false,
            data: $("#settings-form").serialize(),
            success:function(data) {
            }
        });
    }

    function newSetting(){
        $.ajax({
            url: "/warehouse/settings/add?table="+$("#table").val(),
            type: "POST",
            async: false,
            success:function(data) {
                $(".detailsettings").html(data.contentpage);
            }
        });
    }

    function DeleteSetting(id){
        $.ajax({
            url: "/warehouse/settings/delete/id/"+id+"?table="+$("#table").val(),
            type: "POST",
            async: false,
            success: function(data){
            }
        });
    }
</script>
