<?php echo $this->headScript()->prependFile($this->basePath('js/jquery-ui-1.12.1/jquery-ui.js')); ?>
<?php  echo $this->headLink()->prependStylesheet($this->basePath('js/jquery-ui-themes-1.12.1/themes/black-tie/jquery-ui.css')); ?>

<table>
    <tr>
        <td>
            <?php
            $photoAttachment= $this->defaultphoto;
            if (isset($photoAttachment)) {
                echo '<img style="max-height: 120px; width: auto;" src="'. $this->urlthumb . '/' .$photoAttachment->getFileName().'" id="defaultphoto" alt="'.$stock->getDescription().'"/>';
            } else {
                echo '<a id="showform" href=""><img style="max-height: 80px; width: auto;" src="../../../../img/takephoto.png" id="defaultphoto" alt="The photo does not exist"/></a>';
            }
            ?>
        </td>
        <td>
            <h1><?=$stock->getDescription();?></h1>
            <h5>
                Status:
                <?php
                if ($stock->getStatus() == \Warehouse\Controller\InventoryController::ENABLED) {
                    echo '<font color="green">Enabled</font>';
                    if ($stock->getPrefered() == 1) {
                        echo '<font color="black"> - Prefered</font>';
                    }
                }
                else {
                    echo '<font color="red">Disabled</font>';
                    if ($stock->getPrefered() == 1) {
                        echo '<font color="black"> - Prefered</font>';
                    }
                }
                ?>
            </h5>
        </td>
        <td>
            <?='<img src="/warehouse/inventory/barcode/id/'.$stock->getBarcode().'"/>';?>
        </td>
    </tr>
</table>

<hr>

<?php if ($stock->getStockMergement() != null) : ?>
    <p>Short description: <?=$stock->getStockMergement()->getDescription();?></p>
    <p>Area / Section / Supplier: <?=$stock->getStockMergement()->getArea()->getDescription();?> / <?=$stock->getStockMergement()->getSection()->getDescription();?> / <?=$stock->getStockMergement()->getSupplier()->getDescription();?></p>
<?php else: ?>
    <p>Short description: <i>none</i></p>
<?php endif; ?>

<?php if ($stock->getSupplierReference() !== ''): ?>
    <p>Supplier reference: <?=$stock->getSupplierReference();?></p>
<?php else: ?>
    <p>Supplier reference: <i>none</i></p>
<?php endif; ?>
<p>
    Notes:
    <?php if ($stock->getNotes() == ''): ?>
        <i>none</i>
    <?php else: ?>
        <?=$stock->getNotes();?>
    <?php endif; ?>
</p>

<table border="1" border-style="solid" border-color="black" width="50%" cellspacing=4 cellpadding=4>
    <tr>
        <td>
            <p>Current stock:
                <?php if ($stock->getQuantity() > 0) : ?>
                    <font color="green"><?=$stock->getQuantity();?></font>
                <?php else: ?>
                    <font color="red"><?=$stock->getQuantity();?></font>
                <?php endif; ?>
                <?php if ($stock->getStockMergement() != null) : ?>
                    </p><p>Net Quantity: <?=$stock->getNetquantity().$stock->getStockMergement()->getMeasureUnit()->getUnit();?></p>
                <?php else: ?>
                    </p><p>Net Quantity: 0</p>
                <?php endif; ?>
            </p>
        </td>
        <td>
            <p>
                Info Threshold: <?=$stock->getInfothreshold();?>
            </p>
        </td>
        <td>
            <p>
                Critical Threshold: <?=$stock->getCriticalthreshold();?>
            </p>
        </td>
    </tr>
</table>

<hr>

<h4>Attachments</h4>
<form method="POST" name="upload-file-form" enctype="multipart/form-data" action="/warehouse/inventoryattachment/add/id/<?= $stock->getId(); ?>" id="upload-file-form">
    <div class="form-element">
        <input type="file" name="uploaded-file[]" id="uploaded-file">
    </div>
    <button name="add">Add attachment</button>
    <button name="cancel">Cancel</button>
    <input type="text" name="file-label" id="file-label" placeholder="File description"/>
</form>

<span id="error-form-message">
<?php
if ($this->flashmessages) {
    foreach($this->flashmessages as $message) {
        echo $message['message'];
    }
}
?>
</span>
<div id="infoattachment" class="div-info-form-message">
</div>

<?php if (0 === count($stock->getAttachment())): ?>
    <p><i>none</i></p>
<?php endif; ?>

<?php if (0 !== count($stock->getAttachment())): ?>
    <table border="1" border-style="solid" border-color="black" width="65%" cellspacing=4 cellpadding=4>
        <tr>
            <th>Description</th>
            <th>File Name</th>
            <th>Size</th>
            <th>Mime</th>
            <th>Default Photo</th>
            <th></th>
            <th></th>
        </tr>

        <?php foreach($stock->getAttachment() as $attachment): ?>
            <tr>
                <td>
                    <input type="text" name="description<?=$attachment->getId();?>" id="description<?=$attachment->getId();?>" value="<?=$attachment->getDescription();?>">
                    <a id="fileRename" onclick="RenameAttachment(<?=$attachment->getId();?>);" href=""><img style="max-height: 18px; width: auto;" src="../../../../img/edit.jpeg" id="edit" alt=""/></a>
                </td>

                <td><?= $attachment->getFileName(); ?></td>
                <td><?= round($attachment->getSize() / 1000000, 2); ?> MB</td>
                <td><?= $attachment->getMime(); ?></td>

                <?php if ('1' == $attachment->getDefaultPhoto()): ?>
                    <td align="center">
                        <img style="max-height: 18px; width: auto;" src="../../../../img/checkmark.png" id="isdefaultphoto" alt=""/>
                    </td>
                <?php endif; ?>

                <?php if ('1' != $attachment->getDefaultPhoto()): ?>
                    <td align="center">
                        <?php if ('image/png' === $attachment->getMime() or 'image/bmp' === $attachment->getMime() or 'image/jpeg' === $attachment->getMime() or 'image/gif' === $attachment->getMime() or 'image/tiff' === $attachment->getMime()): ?>
                            <a id="choosedefaultphoto" href="/warehouse/inventoryattachment/changedefaultphoto/id/<?= $attachment->getId(); ?>?stock_id=<?=$stock->getId();?>">
                                <img style="max-height: 18px; width: auto;" src="../../../../img/choose2.png" id="choosedefaultphoto" alt=""/>
                            </a>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>

                <td align="center">
                    <a class="filePreview" href="/warehouse/attachment/open/id/<?= $attachment->getId(); ?>" target="_blank">
                        <img style="max-height: 18px; width: auto;" src="../../../../img/view.ico" id="view" alt=""/>
                    </a>
                </td>
                <td align="center">
                    <a id="fileDelete" href="/warehouse/inventoryattachment/delete/id/<?= $attachment->getId(); ?>?stock_id=<?=$stock->getId();?>">
                        <img style="max-height: 18px; width: auto;" src="../../../../img/trash.png" id="delete" alt=""/>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>

<br>

<?php
    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formInput($form->get('backToList'));
    echo ' '.$this->formInput($form->get('update'));
    echo ' '.$this->formInput($form->get('delete'));
    echo ' '.$this->formInput($form->get('add'));
    echo $this->form()->closeTag();
?>
