<script type="text/javascript">
    $(function(ready){
        $("#merge").on('change','select',function () {
            $.ajax({
                url:        '/warehouse/stockmergement/loadunit/id/'+document.getElementsByName("stock[stockmergement_id]")[0].value,
                type:       'POST',
                dataType:   'json',
                async:      false,
                success: function(data){
                    $('#unitfromlabel').html(data.unit);
                },
                error : function(xhr, textStatus, errorThrown) {
                    if (xhr.status === 0) {
                        alert('Not connected. Verify Network.');
                    } else if (xhr.status == 404) {
                        alert('Requested page not found. [404]');
                    } else if (xhr.status == 500) {
                        alert('Server Error [500].');
                    } else if (errorThrown === 'parsererror') {
                        alert('Requested JSON parse failed.');
                    } else if (errorThrown === 'timeout') {
                        alert('Time out error.');
                    } else if (errorThrown === 'abort') {
                        alert('Ajax request aborted.');
                    } else {
                        alert('Remote sever unavailable. Please try later');
                    }
                }
            });
        });
        $("#chkautobarcode").change(function() {
            event.preventDefault();
            if ($(this).is(':checked')){
                $.ajax({
                    type:       'POST',
                    url:        '/warehouse/tools/generatebarcode',
                    dataType:   'json',
                    async:      false,
                    success: function(data){
                        $('#barcode').val(data.barcode);
                    },
                    error : function(xhr, textStatus, errorThrown) {
                        if (xhr.status === 0) {
                            alert('Not connected. Verify Network.');
                        } else if (xhr.status == 404) {
                            alert('Requested page not found. [404]');
                        } else if (xhr.status == 500) {
                            alert('Server Error [500].');
                        } else if (errorThrown === 'parsererror') {
                            alert('Requested JSON parse failed.');
                        } else if (errorThrown === 'timeout') {
                            alert('Time out error.');
                        } else if (errorThrown === 'abort') {
                            alert('Ajax request aborted.');
                        } else {
                            alert('Remote sever unavailable. Please try later');
                        }
                    }
                });
            } else {
                $('#barcode').val('');
            }
        });
    });
</script>

<h1>Update Article</h1>
<?php
$myStock = $this->stock;
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
echo '<div><p>Barcode: '.$this->formInput($this->form->get('stock')->get('barcode')).'  ';
echo $this->fieldRow($this->form->get('stock')->get('chkautobarcode')). ' auto generate';
echo '</p>';
echo '<div><p>Description: '.$this->formTextarea($this->form->get('stock')->get('description'));
echo '</p>';
echo '<div id="merge">';
echo '<p>Short description: ' . $this->formSelect($this->form->get('stock')->get('stockmergement_id'));
echo ' ' .$this->fieldRow($this->form->get('stock')->get('prefered')). ' prefered';
echo '</p></div>';
echo '<div><p>Supplier reference: '.$this->formInput($this->form->get('stock')->get('supplierreference'));
echo '</p>';
echo '</p>';
echo '<div><p>Notes: '.$this->formTextarea($this->form->get('stock')->get('notes'));
echo '</p>';
echo '<hr>';
echo '<p>Quantity: '.$this->formInput($this->form->get('stock')->get('quantity'));
foreach ($this->form->get('stock')->get('quantity')->getMessages() as $inputName => $messageInputs) {
    echo '  <span id="error-form-message">'.$messageInputs.'</span>';
}
echo '</p>';
echo '<p>Info threshold: '.$this->formInput($this->form->get('stock')->get('infothreshold'));
echo '</p>';
echo '<p>Critical threshold: '.$this->formInput($this->form->get('stock')->get('criticalthreshold'));
echo '</p>';
echo '<hr>';
echo '<div><p>Net Quantity: '.$this->formRow($this->form->get('stock')->get('netquantity')).' <span id="unitfromlabel" name ="unitfromlabel">';
if ($myStock->getStockMergement() != null)
    echo $myStock->getStockMergement()->getMeasureUnit()->getUnit().'</span>';
else
    echo '</span>';
echo '</p>';
echo '<p>Status: '.$this->formSelect($this->form->get('stock')->get('status'));
echo '</p>';
echo '<hr>';
echo '<hr>';
echo $this->formInput($form->get('backToList'));
echo ' '.$this->formInput($form->get('update'));
echo ' '.$this->formInput($form->get('cancel'));
echo $this->form()->closeTag();
?>
<br>
