<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>

<table>
    <tr>
        <td width="130" valign="middle">
            Old password:
        </td>
        <td align="right">
            <div> <?=$this->formElement($form->get('password')->get('password'));?></div>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <div><?=$this->formElementErrors($form->get('password')->get('password'), array('class' => 'custom_form_errors'));?></div>
        </td>
    </tr>
    <tr>
        <td width="130" valign="middle">
            <?=$form->get('password')->get('newpassword1')->getLabel();?>
        </td>
        <td align="right">
            <?=$this->formInput($form->get('password')->get('newpassword1'));?>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <div><?=$this->formElementErrors($form->get('password')->get('newpassword1'), array('class' => 'custom_form_errors'));?></div>
        </td>
    </tr>
    <tr>
        <td width="130" valign="middle">
            <?=$form->get('password')->get('newpassword2')->getLabel();?>
        </td>
        <td align="right">
            <?=$this->formInput($form->get('password')->get('newpassword2'));?>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <div><?=$this->formElementErrors($form->get('password')->get('newpassword2'), array('class' => 'custom_form_errors'));?></div>
        </td>
    </tr>
    <tr>
        <td colspan="3" align="right">
            <span id="error-form-message">
                <?php if ($this->messages):?>
                    <?php foreach($this->messages as $message):?>
                        <?= $message;?>
                    <?php endforeach;?>
                <?php endif;?>

                <?php if ($this->flashmessages):?>
            </span>
            <span class="custom_form_info">
                <?php foreach($this->flashmessages as $message):?>
                    <?= $message;?>
                <?php endforeach;?>
                <?php endif;?>
            </span>
        </td>
    </tr>
    <tr>
        <td colspan="2" align="right">
            <?=$this->formInput($form->get('cancel'));?>
            <?=$this->formInput($form->get('update'));?>
        </td>
    </tr>
    <tr>
        <td colspan="2"></td>
    </tr>
</table>
<?= $this->form()->closeTag(); ?>
