

<h4>Upload a file !!</h4>



<?php

/*
$formUploadFile = $this->form;
$formUploadFile->prepare(); // The correct enctype is set here
$formUploadFile->setAttribute('action', '/warehouse/test/uploadfile');
echo $this->form()->openTag($formUploadFile);
//   echo $this->formFileSessionProgress(); // Must come before the file input!

echo '<div class="form-element">';
$fileElement = $formUploadFile->get('attachment-file');
//echo $this->formLabel($fileElement);
echo $this->formFile($fileElement);
echo $this->formElementErrors($fileElement);
echo '</div>';
echo '<button>Add new attachment</button>';
echo $this->form()->closeTag();
*/

?>


